apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::117647030715:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-iGm3ABwWwOw9
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::117647030715:user/yash
      username: yash
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::117647030715:user/suresh
      username: suresh    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-11T11:56:33Z"
  name: aws-auth
  namespace: kube-system
  uid: 66be870c-7899-4b93-a2ad-ed050519e2f7
